// generated by stringer -type CallType; DO NOT EDIT

package query

import "fmt"

const _CallType_name = "SelectInsertUpdateDelete"

var _CallType_index = [...]uint8{0, 6, 12, 18, 24}

func (i CallType) String() string {
	if i < 0 || i+1 >= CallType(len(_CallType_index)) {
		return fmt.Sprintf("CallType(%d)", i)
	}
	return _CallType_name[_CallType_index[i]:_CallType_index[i+1]]
}
